const images = {
  activity: require('./images/activity.png'),
  activity_selected: require('./images/activity_selected.png'),
  add: require('./images/add.png'),
  add_selected: require('./images/add_selected.png'),
  home: require('./images/home.png'),
  home_selected: require('./images/home_selected.png'),
  profile: require('./images/profile.png'),
  profile_selected: require('./images/profile_selected.png'),
  search: require('./images/search.png'),
  search_selected: require('./images/search_selected.png'),
  photo_camera: require('./images/photo_camera.png'),
  direct_message: require('./images/direct_message.png'),
  logo: require('./images/logo.png'),
  more: require('./images/more.png'),
  bookmark: require('./images/bookmark.png'),
  like: require('./images/like.png'),
  comment: require('./images/comment.png'),
  settings: require('./images/settings.png'),
  flash: require('./images/flash.png'),
  close: require('./images/close.png'),
  logoBlack: require('./images/logoBlack.png'),
  facebookLogo: require('./images/facebookLogo.png'),
  backButton: require('./images/backButton.png'),
  plusIcon: require('./images/plusIcon.png'),
  test: require('./images/test.png'),
  addIcon: require('./images/addIcon.png'),
  searchInputIcon: require('./images/searchInputIcon.png'),
  dmBackButton: require('./images/dmBackButton.png'),
  redHeart: require('./images/redHeart.png'),
  bookmarkWhite: require('./images/bookmarkWhite.png'),
  videoCamera: require('./images/video_camera.png'),
  write: require('./images/write.png'),
  dot: require('./images/dot.png'),
  dmBottomCamera: require('./images/dmBottomCamera.png'),
  grid: require('./images/gridIcon.png'),
  list3: require('./images/list3.png'),
};

export default images;
