sudo: false
language: node_js
node_js:
- '12.18.3'
branches:
  only:
  - master
cache:
  directories:
  - node_modules
before_install:
- npm update
install:
- npm install
- yarn install
script:
- npm run lint
- npm run test

